### ISSUE TITLE
help with docker compose

### ISSUE THREAD

**Issue by juan11perez** [Mumie-hub/docker-services#32]
Good day, thank you for producing/sharing this component. I've been trying to get it to work for a couple of days unusccesfully. This is my compoe:

```
  rclone:
    container_name: rclone
    image: mumiehub/rclone-mount
    restart: unless-stopped
    privileged: true    
    cap_add:
    - SYS_ADMIN    
    devices:
    - /dev/fuse
    security_opt:
    - apparmor:unconfined    
    volumes:
    - /home/juan/Documents/docker/rclone/.rclone.conf:/config/.rclone.conf 
    - /home/juan/Documents/gdrive:/mnt/mediaefs:shared
    environment:
    - PGID=1001
    - PUID=1000
    - TZ=Asia/Dubai
    - RemotePath="gdrive"
    - MountCommands=--allow-other --allow-non-empty --dir-cache-time 48h --poll-interval 5m --buffer-size 128M    
    - MountPoint="/mnt/mediaefs"
```
Docker log shows the following:
Mounting "gdrive" to "/mnt/mediaefs" at: 2019.08.16-06:24:52
but gdrive doesnt load. 

Welcome any advice. Thank you
