### ISSUE TITLE
Other Docker Container cannot see content of mounted volume

### ISSUE THREAD

**Issue by sebastianborggrewe** [Mumie-hub/docker-services#40]
Hi,
I am trying since 2 days to get the contents of my google drive into a docker volume, which is shared between the google-drive-cloud container and my story-worker.

The sync in the google-drive-cloud container works fine and I can see the files. However the volume on the story-worker stays empty.

Any idea, how this can be solved. Thanks a lot in advance 

```version: '3'
services:
  google-drive-cloud:
    image: mumiehub/rclone-mount
    container_name: google-drive-cloud
    restart: always
    privileged: true
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./docker/google-drive-cloud:/config
      - google-drive:/mnt/gsuite
    environment:
      - "MountPoint=/mnt/gsuite"
      - "RemotePath=gsuite:"
      - "MountCommands=--allow-other --allow-non-empty"
  story-worker:
    container_name: story-worker
    build: ./docker/story-worker
    volumes:
      - google-drive:/data
volumes:
  google-drive:

**Comment by Mumie-hub** [comment]
Your are missing the mendatory command :shared in both volume mounts. Look at the docker-compose example in the repo: [rclone-mount/docker-compose.yml](https://github.com/Mumie-hub/docker-services/blob/master/rclone-mount/docker-compose.yml). If you want to understand the behavior, google for mount propagation :)! Iam not quite sure if docker volumes will work. Instead you should use a host path:

`- /mnt/google-drive:/mnt/gsuite:shared`
`- /mnt/google-drive:/data:shared`

Best Regards

**Comment by sebastianborggrewe** [comment]
Hey @Mumie-hub,
thanks for the reply. I actually solved it differently. Turns out: Docker volumes do not work.
So the image does not really work for my use case. However, your image is the only one that syncs really well. So if you ever figure out how to make this work with a docker volume, let me know :)

A Story worker.. :-) It is a worker that processes audio stories ;-)

**Comment by Mumie-hub** [comment]
it is possible to set the propagation for volumes in a docker-compose file [docs.docker.com - volumes](https://docs.docker.com/compose/compose-file/compose-file-v2/#volumes)
like so:
```
volumes:
    - type: bind
      bind:
          propagation: shared
```
but why not just use a host path?
as in your example:
```
version: '2'
services:
  google-drive-cloud:
    image: mumiehub/rclone-mount
    container_name: google-drive-cloud
    restart: always
    privileged: true
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./docker/google-drive-cloud:/config
      - /mnt/google-drive:/mnt/gsuite:shared
    environment:
      - "MountPoint=/mnt/gsuite"
      - "RemotePath=gsuite:"
      - "MountCommands=--allow-other --allow-non-empty"
  story-worker:
    container_name: story-worker
    build: ./docker/story-worker
    volumes:
      - /mnt/google-drive:/data:shared
volumes:
  google-drive:
```

Greetings from Munich :)!
