### ISSUE TITLE
Shared folder is not updated outside of container

### ISSUE THREAD

**Issue by LeidenSpain** [Mumie-hub/docker-services#51]
I have been using the container perfectly (it works really well) but suddenly, I find that without having done anything, the content of the mounted unit is not updated (GDrive)

If I access the unit from other containers or from the system (Lubuntu 20.04) I don't see the new files added (by web browser).
But if I enter the rclone container and access the unit by console, if I see the new files.

I have looked to update the cache file in case it solved something, but I did not know how to do it

**Comment by ClemTheStudent** [comment]
Added these caps resolved the problem for me: 
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - MKNOD
source: https://docs.docker.com/engine/reference/run/

**Comment by blastbeng** [comment]
Hi, I think the issue it's still there, I'm using docker compose as follow

`version: '3.3'
services:
  rclone-mount:
    container_name: rclone-mount-${NAME}
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - MKNOD
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    environment:
      - 'RemotePath=$NAME:/'
      - 'MountPoint=/mnt/$NAME'
      - 'ConfigDir=/config'
      - 'ConfigName=$NAME.conf'
      - 'MountCommands=--allow-non-empty --use-mmap --vfs-cache-mode writes --allow-other --dir-cache-time=10s --cache-info-age=10s --cache-tmp-upload-path=/mnt/microsd/tmp/rclone/upload --cache-chunk-path=/mnt/microsd/tmp/rclone/chunks --cache-dir=/mnt/microsd/tmp/rclo>
    volumes:
      - '/rclone/$NAME.conf:/config/$NAME.conf'
      - '/mnt/$NAME:/mnt/$NAME:/'
      - '/mnt/microsd/tmp:/mnt/microsd/tmp'
    image: mumiehub/rclone-mount
    restart: unless-stopped`

And in env file: NAME=mycustomname

If i access the container i can see the files under /mnt/$NAME but when i go to the host mount point i see nothing. Looks like docker can't correctly mount the mnt directory.... Any help?

**Comment by fede8802** [comment]
I had the same problem and solve it by seting the propagation as shared.

Try to do the following with the volumes declaration:

      - type: bind
        source: '/my/custom/mountpoint/$NAME'
        target: '/mnt/$NAME:/'
        bind:
          propagation: shared

**Comment by blastbeng** [comment]
@fede8802 You're my savior!

I can confirm that this is the correct configuration using docker-compose:

```
version: '3.3'
services:
  rclone-mount:
    container_name: rclone-mount-${NAME}
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - MKNOD
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse
    environment:
      - 'RemotePath=$NAME:/'
      - 'MountPoint=/mnt/$NAME'
      - 'ConfigDir=/config'
      - 'ConfigName=$NAME.conf'
      - 'MountCommands=--allow-non-empty --allow-other'
    volumes:
      - '/my/custom/confdir/$NAME.conf:/config/$NAME.conf'
      - type: bind
        source: '/my/custom/mountpoint/$NAME'
        target: '/mnt/$NAME'
        bind:
          propagation: shared
    image: mumiehub/rclone-mount
    restart: unless-stopped
```


Now when using df i see the mount!

`mycustomname:/    20G  9,7G     11G  49% /var/lib/mailservermega/mnt/mycustomname`
