### ISSUE TITLE
ERROR: for rclone-mount  Cannot start service rclone-mount: path /host_mnt/Users/jandrop/mnt/gdrive is mounted on /host_mnt but it is not a shared mount

### ISSUE THREAD

**Issue by jandrop** [Mumie-hub/docker-services#52]
I´m getting this error when I start the docker image, if I remove the :shared from the volume the service starts but is not sharing the content with the external volume.

I don´t know if this is an issue because of me or is something in your docker image.
```
ERROR: for rclone-mount  Cannot start service rclone-mount: path /host_mnt/Users/jandrop/mnt/gdrive is mounted on /host_mnt but it is not a shared mount
```

This is my docker compose:

```
version: "3"
services: 
  rclone-mount:
    image: mumiehub/rclone-mount
    restart: unless-stopped
    ports:
    - '80:80'
    cap_add:
    - SYS_ADMIN
    security_opt: 
    - 'apparmor:unconfined'
    volumes: 
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
    - '/Users/myUser/developer/docker/rclone/.config/rclone:/config'
    - '/Users/myUser/mnt/gdrive:/mnt/mediaefs:shared'
    logging: 
      options: 
        max-size: 1g
    container_name: rclone-mount
    devices:
    - /dev/fuse
    environment: 
    - 'RemotePath=gdrive:'
    - 'MountCommands=--allow-other --allow-non-empty --buffer-size 256M'
    - 'ConfigName=rclone.conf'
```
