### ISSUE TITLE
Something with the config location not working correctly

### ISSUE THREAD

**Issue by trbntwo** [Mumie-hub/docker-services#62]
Possibly related to #39
The container does not find the configuration file, although it has the folder and also recognizes the correct name.
Exact Config:
The configuration is on the host system under 
```
/home/torben/Docker/NextcloudForJellyfin/config/rclone.conf
```
The ``docker-compose.yaml``:
```
version: "3"
services:
  rclone-mount:
    image: mumiehub/rclone-mount
    container_name: NextcloudForJellyfin
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/torben/Docker/NextcloudForJellyfin/config:/config
      - /home/torben/Docker/Jellyfin/Mediathek:/mediaefs:shared
    environment:
      - ConfigName=rclone.conf
      - RemotePath=NextcloudForJellyfin:Mediathek
      - MountCommands=--allow-other --buffer-size 256M --vfs-cache-mode full --allow-non-empty
```
The problem I noticed when I run ``docker compose up`` without the ``-d`` flag
```
2023/03/03 14:34:57 NOTICE: Config file "/config/rclone.conf" not found - using defaults
```
The whole "log"
```
NextcloudForJellyfin  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
NextcloudForJellyfin  | [s6-init] ensuring user provided files have correct perms...exited 0.
NextcloudForJellyfin  | [fix-attrs.d] applying ownership & permissions fixes...
NextcloudForJellyfin  | [fix-attrs.d] done.
NextcloudForJellyfin  | [cont-init.d] executing container initialization scripts...
NextcloudForJellyfin  | [cont-init.d] 20-init: executing... 
NextcloudForJellyfin  | [cont-init.d] 20-init: installing system updates
NextcloudForJellyfin  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
NextcloudForJellyfin  | fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
NextcloudForJellyfin  | OK: 8 MiB in 20 packages
NextcloudForJellyfin  | [cont-init.d] 20-init: exited 0.
NextcloudForJellyfin  | [cont-init.d] 30-check: executing... 
NextcloudForJellyfin  | [cont-init.d] 30-check: MountPoint /mnt/mediaefs is ready
NextcloudForJellyfin  | [cont-init.d] 30-check: exited 0.
NextcloudForJellyfin  | [cont-init.d] done.
NextcloudForJellyfin  | [services.d] starting services
NextcloudForJellyfin  | [services.d] [rclone-mount]-run: starting rclone mount 2023.03.03-14:34:57
NextcloudForJellyfin  | [services.d] done.
NextcloudForJellyfin  | 2023/03/03 14:34:57 NOTICE: Config file "/config/rclone.conf" not found - using defaults
NextcloudForJellyfin  | 2023/03/03 14:34:57 Failed to create file system for "NextcloudForJellyfin:Mediathek": didn't find section in config file
NextcloudForJellyfin  | [services.d] [rclone-mount]-finish: rclone process not present, restarting container[ERROR]
NextcloudForJellyfin  | [services.d] [rclone-mount]-finish: waiting for rclone shutdown
NextcloudForJellyfin  | [cont-finish.d] executing container finish scripts...
NextcloudForJellyfin  | [cont-finish.d] 20-unmount: executing... 
NextcloudForJellyfin  | [cont-finish.d] 20-unmount: waiting for shutdown of all services
NextcloudForJellyfin  | umount: can't unmount /mnt/mediaefs: Invalid argument
NextcloudForJellyfin  | [cont-finish.d] 20-unmount: successful unmounted
NextcloudForJellyfin  | [cont-finish.d] 20-unmount: exited 0.
NextcloudForJellyfin  | [cont-finish.d] done.
NextcloudForJellyfin  | [s6-finish] waiting for services.
NextcloudForJellyfin  | [s6-finish] sending all processes the TERM signal.
NextcloudForJellyfin  | [s6-finish] sending all processes the KILL signal and exiting.
NextcloudForJellyfin exited with code 0
```
